FROM nginx:1.23.0-alpine
#Install tools
RUN apk add vim \
    && apk add curl \
    && apk add nano;

COPY ./Assets /usr/share/nginx/site/dist/
COPY index.html /usr/share/nginx/site/dist/
COPY Style.css /usr/share/nginx/site/dist/
COPY Lato-Regular.ttf /usr/share/nginx/site/dist/

COPY .devops/conf/default.conf /etc/nginx/conf.d/default.conf
COPY .devops/conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8085
CMD [ "nginx" , "-g" , "daemon off;"]