FROM nginx:1.23.0-alpine
#Install tools
RUN apk add vim \
    && apk add curl \
    && apk add nano;

COPY ./ /usr/share/nginx/site/dist/

COPY .devops/conf/default.conf /etc/nginx/conf.d/default.conf
COPY .devops/conf/nginx.conf /etc/nginx/nginx.conf

EXPOSE 8083
CMD [ "nginx" , "-g" , "daemon off;"]